Aztech/Controllers/AdminModifyAccountController.cs
using Aztech.Models;
using Aztech.Services;
using Aztech.ViewModels.CustomerModifyAccount;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Aztech.Controllers
{
    [Authorize]
    public class AdminModifyAccountController : Controller
    {
        IDataServices dataServices;
        UserManager<IdentityModel> userManager;
        SignInManager<IdentityModel> signInManager;
        public AdminModifyAccountController(IDataServices dataServices, UserManager<IdentityModel> userManager, SignInManager<IdentityModel> signInManager)
        {
            this.dataServices = dataServices;
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        [HttpGet]
        public async Task<IActionResult> ModifyAdminAccount()
        {
            IdentityModel iDMod = await userManager.GetUserAsync(User);
            if (iDMod.UserAuthority !=  2) return RedirectToAction("Index", "Home");

            AppUser user = dataServices.GetAppUsers().Where(r => r.AppUserId == iDMod.AppUserId).ToList()[0];
            CustomerUpdateViewModel model = new CustomerUpdateViewModel();
            model.Company = user.Company;
            model.FirstName = user.FirstName;
            model.LastName = user.LastName;
            model.Email = user.Email;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ModifyAdminAccount(CustomerUpdateViewModel inputModel)
        {
            if (!ModelState.IsValid)
            {
                return View(inputModel);
            }
            IdentityModel iDMod = await userManager.GetUserAsync(User);
            AppUser user = dataServices.GetAppUsers().Where(r => r.AppUserId == iDMod.AppUserId).ToList()[0];
            var results = await signInManager.CheckPasswordSignInAsync(iDMod, inputModel.OldPassword, false);
            if (!results.Succeeded)
            {
                ModelState.AddModelError("", "Invalid old password.");
                inputModel.OldPassword = "";
                inputModel.NewPassword = "";
                return View(inputModel);
            }


            var token = await userManager.GeneratePasswordResetTokenAsync(iDMod);
            var results2 = await userManager.ResetPasswordAsync(iDMod, token.ToString(), inputModel.NewPassword);
            if (!results2.Succeeded)
            {
                ModelState.AddModelError("", "New Password invalid or taken.");
                return View(inputModel);
            }

            iDMod.Email = inputModel.Email;
            var results3 = await userManager.UpdateAsync(iDMod);
            if (!results3.Succeeded)
            {
                throw new Exception("Problem updating Identity Model async");
            }

            user.Company = inputModel.Company;
            user.Email = inputModel.Email;
            user.FirstName = inputModel.FirstName;
            user.LastName = inputModel.LastName;
            user.Password = "";
            dataServices.UpdateAppUser(user);

            return RedirectToAction("Index", "Home");



        }
    }
}

Aztech/Controllers/CustomerTablesController.cs
using Aztech.Models;
using Aztech.Services;
using Aztech.ViewModels.CustomerTables;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Aztech.Controllers
{
    [Authorize]
    public class CustomerTablesController : Controller
    {
        IDataServices dataServices;
        public CustomerTablesController(IDataServices dataServices)
        {
            this.dataServices = dataServices;
        }

        public IActionResult OpenOrdersTable(int appUserId)
        {
            OpenOrdersTableViewModel model = new OpenOrdersTableViewModel();
            model.CustomerProfile = dataServices.GetAppUsers().Where(r => r.AppUserId == appUserId).ToList()[0];
            model.AllOrders = dataServices.GetCustomerOpenPartOrders(appUserId);
            return View(model);
        }

        public IActionResult ShipmentsTable(int appUserId)
        {
            ShipmentsTableViewModel model = new ShipmentsTableViewModel();
            model.AppUserId = appUserId;
            model.Shipments = dataServices.GetCustomerShipments(appUserId);
            model.ShippedPartsByShipmentId = dataServices.GetShippedPartsGroupedByShipment(appUserId);
            return View(model);
            
        }

        public IActionResult InvoicesTable(int appUserId)
        {
            InvoicesTableViewModel model = new InvoicesTableViewModel();
            model.AppUserId = appUserId;
            model.Invoices = dataServices.GetInvoicesFor(appUserId);
            return View(model);
        }

        public IActionResult PartsTable(int appUserId)
        {
            PartsTableViewModel model = new PartsTableViewModel();
            model.AppUserId = appUserId;
            model.parts = dataServices.GetPartsForUser(appUserId);
            return View(model);
        }

        public IActionResult QuotesTable(int appUserId)
        {
            QuotesTableViewModel model = new QuotesTableViewModel();
            model.Quotes = dataServices.GetQuotesForUser(appUserId);
            model.AppUserId = appUserId;
            return View(model);
        }

        public IActionResult InvoicePdf(int invoiceId)
        {
            Invoice invoice = dataServices.GetInvoice(invoiceId);
            byte[] pdfBinary; 
           
            using (MemoryStream mem = new MemoryStream())
            {
                Document doc = new Document(iTextSharp.text.PageSize.LETTER, 10, 10, 42, 35);
                PdfWriter wri = PdfWriter.GetInstance(doc, mem);
                Paragraph invoiceNum = new Paragraph("Invoice# " + invoice.InvoiceNum);
                Paragraph userPar = new Paragraph("User: " + invoice.AppUserId);
                Paragraph invoiceDatePar = new Paragraph("Invoice Date: " + invoice.InvoiceDate);
                Paragraph invoiceAmt = new Paragraph("Invoice Ammount: " + invoice.InvoiceAmt);
                Paragraph balPar = new Paragraph("Balance Due" + invoice.BalanceDue);
                doc.Open();
                doc.Add(invoiceNum);
                doc.Add(userPar);
                doc.Add(invoiceDatePar);
                doc.Add(invoiceAmt);
                doc.Add(balPar);
                doc.Close();
                wri.Close();

                //Must close doc before returning binary array from mem. 
                pdfBinary = mem.ToArray();
            }

            return File(pdfBinary, "application/pdf");
        }

        public IActionResult MaterialCertification(int appUserId)
        {
            byte[] pdfBinary; 

            using(MemoryStream mem = new MemoryStream())
            {
                Document doc = new Document(iTextSharp.text.PageSize.LETTER, 10, 10, 42, 35);
                PdfWriter pdfWriter = PdfWriter.GetInstance(doc, mem);
                Paragraph par = new Paragraph("Material Certificate for user: " + appUserId);
                doc.Open();
                doc.Add(par);
                doc.Close();
                pdfWriter.Close();

                //Must close doc before returning binary array from mem. 
                pdfBinary = mem.ToArray(); 
            }

            return File(pdfBinary, "application/pdf");
        }

        public IActionResult PackingSlip(int appUserId)
        {
            byte[] pdfBinary;

            using (MemoryStream mem = new MemoryStream())
            {
                Document doc = new Document(iTextSharp.text.PageSize.LETTER, 10, 10, 42, 35);
                PdfWriter pdfWriter = PdfWriter.GetInstance(doc, mem);
                Paragraph par = new Paragraph("Packing Slip for user: " + appUserId);
                doc.Open();
                doc.Add(par);
                doc.Close();
                pdfWriter.Close();

                //Must close doc before returning binary array from mem. 
                pdfBinary = mem.ToArray();
            }

            return File(pdfBinary, "application/pdf");
        }
    }

}

Aztech/Controllers/NewCustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using Aztech.Data;
using Aztech.Models;
using Aztech.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Aztech.Controllers
{
    [Authorize]
    public class NewCustomerController : Controller
    {
        IDataServices dataServices;
        PasswordGen passGen; 
        UserManager<IdentityModel> userManager;
        public NewCustomerController(IDataServices dataServices, UserManager<IdentityModel> userManager, PasswordGen passGen)
        {
            this.dataServices = dataServices;
            this.userManager = userManager;
            this.passGen = passGen; 
        }

        [HttpGet]
        public async Task<IActionResult> AddCustomer()
        {
            IdentityModel user = await userManager.GetUserAsync(User);
            if (user.UserAuthority < 2)
            {
                return RedirectToAction("Index", "Home");
            }

            AppUser customer = new AppUser();
            customer.Type = "Customer";
            return View(customer);
        }

        [AutoValidateAntiforgeryToken]
        [HttpPost]
        public async Task<IActionResult> AddCustomer(AppUser customer)
        {
            IdentityModel user = await userManager.GetUserAsync(User);
            if (user.UserAuthority < 2)
            {
                return RedirectToAction("Index", "Home");
            }

            if (!ModelState.IsValid)
            {
                return View(customer);
            }
            customer.FirstLogin = "N/A";
            if(dataServices.AddAppUser(customer) != true)
            {
                throw new Exception("Failed to create customer model");
            }
            IdentityModel iUser = new IdentityModel();
            iUser.Email = customer.Email;
            iUser.AppUserId = customer.AppUserId;
            iUser.UserName = customer.Email;
            iUser.SimulationCode = -1;
            iUser.UserAuthority = 1;

            customer.Password = passGen.GetPassword(); 
            var result = await userManager.CreateAsync(iUser, customer.Password);
            if (!result.Succeeded)
            {
                if(dataServices.DeleteAppUser(customer) != true)
                {
                    throw new Exception("Faileed to both create Identity User and to delete customer model");
                }
                throw new Exception("Failed to create user"); 
            }


            string body = "Hello an account has been created for you. Use this email and the following temporary password to log in" + 
                          "It is highly reccomended that you change your password upon your first log in." + 
                           "   Temporary Password: " + customer.Password;
            var smtpClient = new SmtpClient
            {
                Host = "smtp.aol.com",
                Port = 587,
                EnableSsl = true,
                Credentials = new NetworkCredential("stevend39addario@aol.com", "C1c3r0Th3Th1rd")
            };
            using (var message = new MailMessage("stevend39addario@aol.com", customer.Email) { Subject = "Account Creation", Body = body })
            {
                smtpClient.Send(message);
            }
            return RedirectToAction("Index", "Home"); 
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult CustomerCreate()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }

            AppUser customer = new AppUser();
            customer.Type = "Customer";
            return View(customer);
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CustomerCreate(AppUser customer)
        {
            if (!ModelState.IsValid)
            {
                return View(customer);
            }
            customer.FirstLogin = "N/A";
            if (dataServices.AddAppUser(customer) != true)
            {
                throw new Exception("Failed to create customer model");
            }
            IdentityModel iUser = new IdentityModel();
            iUser.Email = customer.Email;
            iUser.AppUserId = customer.AppUserId;
            iUser.UserName = customer.Email;
            iUser.SimulationCode = -1;
            iUser.UserAuthority = 1;

            customer.Password = passGen.GetPassword();
            var result = await userManager.CreateAsync(iUser, customer.Password);
            if (!result.Succeeded)
            {
                if (dataServices.DeleteAppUser(customer) != true)
                {
                    throw new Exception("Faileed to both create Identity User and to delete customer model");
                }
                throw new Exception("Failed to create user");
            }


            string body = "Hello an account has been created for you. Use this email and the following temporary password to log in" +
                          "It is highly reccomended that you change your password upon your first log in." +
                           "   Temporary Password: " + customer.Password;
            var smtpClient = new SmtpClient
            {
                Host = "smtp.aol.com",
                Port = 587,
                EnableSsl = true,
                Credentials = new NetworkCredential("stevend39addario@aol.com", "C1c3r0Th3Th1rd")
            };
            using (var message = new MailMessage("stevend39addario@aol.com", customer.Email) { Subject = "Account Creation", Body = body })
            {
                smtpClient.Send(message);
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

Aztech/Views/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @*<link rel="stylesheet" href="node_modules/bootstrap/dist/css/bootstrap.css" />
        <script src="node_modules/bootstrap/dist/js/bootstrap.js"></script>
        <script src="node_modules/bootstrap/dist/jquery.js"></script>
        <script src="node_modules/popper.js/dist/popper.js"></script>*@

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <style>
        nav a, div a {
            color: white;
            margin-top: 20%;
            font-size: large;
            margin-right: 2%;
        }

        nav {
            padding-left: 5%;
            padding-top: 2%;
            padding-bottom: 2%;
        }
    </style>
</head>
<body style="background-color: white; height: 100%; width: 100%">
    <div style="margin-top: 5%; margin-left: 5%; background-color: white; height: 100%; margin-bottom: 0px">
        <nav class="navbar" style="background-color: #ACB0AF; margin-bottom: 0px">
            <span class="navbar-left" style="margin-right: 10%; margin-bottom: 0px"><a style="font-size: x-large" asp-action="Index" asp-controller="Home"><img src="~/earlMilton.jpg" style="width: 5%; height: 5%; margin-bottom: 0px" /></a></span>


            @*@if (User.Identity.IsAuthenticated)
            {
                @inject Microsoft.AspNetCore.Identity.UserManager<Aztech.Models.IdentityModel> userManager;
                Aztech.Models.IdentityModel user = await userManager.GetUserAsync(User);
                @if (user.UserAuthority > 1 && user.SimulationCode == -1)
                {

                    <a asp-action="Index" asp-controller="Home">Home&nbsp;</a>
                    @if (!ViewBag.Title.Equals("Add Customer"))
                    {
                        <a asp-action="AddCustomer" asp-controller="NewCustomer">Create Customer Account&nbsp;</a>

                    }
                    @if (user.UserAuthority == 2)
                    {
                        <a asp-action="ModifyAdminAccount" asp-controller="AdminModifyAccount">&nbsp;Update Account Information &nbsp;</a>
                    }
                    @if (user.UserAuthority > 2)
                    {
                        if (!ViewBag.Title.Equals("Add Admin"))
                        {
                            <a asp-action="AddAdmin" asp-controller="NewAdmin">Create Admin Account&nbsp;</a>
                        }
                        if (!ViewBag.Title.Equals("All Admins"))
                        {
                            <a asp-action="GetAdmins" asp-controller="NewAdmin">All Admins</a>
                        }

                        if (!ViewBag.Title.Equals("Create Part"))
                        {
                            <a asp-controller="Parts" asp-action="CreatePart">Create Part</a>
                        }
                    }

                }
                else if (user.UserAuthority > 1)
                {
                    <a asp-action="ExitSimulation" asp-controller="Account">Exit Simulation&nbsp;</a>
                    <a asp-action="Index" asp-controller="Home">Open Orders </a>
                    <a asp-action="ShipmentsTable" asp-controller="CustomerTables" asp-route-appUserId="@user.SimulationCode">Shipments&nbsp;</a>
                    <a asp-action="InvoicesTable" asp-controller="CustomerTables" asp-route-appUserId="@user.SimulationCode">Invoices&nbsp;</a>
                    <a asp-action="PartsTable" asp-controller="CustomerTables" asp-route-appUserId="@user.SimulationCode">Part Activity&nbsp;</a>
                    <a asp-action="QuotesTable" asp-controller="CustomerTables" asp-route-appUserId="@user.SimulationCode">Quotes&nbsp;</a>
                }

                else
                {
                    <a asp-action="Index" asp-controller="Home">Open Orders </a>
                    <a asp-action="ShipmentsTable" asp-controller="CustomerTables" asp-route-appUserId="@user.AppUserId">Shipments&nbsp;</a>
                    <a asp-action="InvoicesTable" asp-controller="CustomerTables" asp-route-appUserId="@user.AppUserId">Invoices &nbsp;</a>
                    <a asp-action="PartsTable" asp-controller="CustomerTables" asp-route-appUserId="@user.AppUserId">Part Activity&nbsp;</a>
                    <a asp-action="QuotesTable" asp-controller="CustomerTables" asp-route-appUserId="@user.AppUserId">Quotes&nbsp;</a>
                    <a asp-action="ModifyCustomerAccount" asp-controller="CustomerModifyAccount">Update Acount&nbsp;</a>
                }

                <a asp-action="AllParts" asp-controller="Parts">View Part Prices</a>
                <a asp-action="Logout" asp-controller="Account">Sign Out&nbsp;</a>
            }*@
        </nav>
        <div style="height: 90vh; background-color: #ACB0AF; width: 8%; font-size: large; float: left; margin-top: 0px; padding-left: 1%" class="text-white linke-white">

            <br /><br /><br /><br /><br /><br />
            @if (User.Identity.IsAuthenticated)
            {
                @inject Microsoft.AspNetCore.Identity.UserManager<Aztech.Models.IdentityModel> userManager;
                Aztech.Models.IdentityModel user = await userManager.GetUserAsync(User);
                @if (user.UserAuthority > 1 && user.SimulationCode == -1)
                {

                    <a asp-action="Index"  asp-controller="Home">Home</a> <br /><br />
                    @if (!ViewBag.Title.Equals("Add Customer"))
                    {
                        <a asp-action="AddCustomer" asp-controller="NewCustomer">Create Customer</a><br /><br />

                    }
                    @if (user.UserAuthority == 2)
                    {
                        <a asp-action="ModifyAdminAccount" asp-controller="AdminModifyAccount">&nbsp;Update Account</a><br /><br />
                    }
                    @if (user.UserAuthority > 2)
                    {
                        if (!ViewBag.Title.Equals("Add Admin"))
                        {
                            <a asp-action="AddAdmin" asp-controller="NewAdmin">Create Admin</a><br /><br />
                        }
                        if (!ViewBag.Title.Equals("All Admins"))
                        {
                            <a asp-action="GetAdmins" asp-controller="NewAdmin">All Admins</a><br /><br />
                        }

                        @*if (!ViewBag.Title.Equals("Create Part"))
                        {
                            <a asp-controller="Parts" asp-action="CreatePart">Create Part</a><br /><br />
                        }*@
                    }

                }
                else if (user.UserAuthority > 1)
                {
                    <a asp-action="ExitSimulation" asp-controller="Account">Exit <br /> Simulation&nbsp;</a><br /><br />
                    <a asp-action="Index" asp-controller="Home">Open Orders </a> <br /><br />
                    <a asp-action="ShipmentsTable" asp-controller="CustomerTables" asp-route-appUserId="@user.SimulationCode">Shipments</a><br /><br />
                    <a asp-action="InvoicesTable" asp-controller="CustomerTables" asp-route-appUserId="@user.SimulationCode">Invoices</a><br /><br />
                    <a asp-action="PartsTable" asp-controller="CustomerTables" asp-route-appUserId="@user.SimulationCode">Part Activity</a><br /><br />
                    <a asp-action="QuotesTable" asp-controller="CustomerTables" asp-route-appUserId="@user.SimulationCode">Quotes</a><br /><br />
                }

                else
                {
                    <a asp-action="Index" asp-controller="Home">Open Orders </a><br /><br />
                    <a asp-action="ShipmentsTable" asp-controller="CustomerTables" asp-route-appUserId="@user.AppUserId">Shipments;</a><br /><br />
                    <a asp-action="InvoicesTable" asp-controller="CustomerTables" asp-route-appUserId="@user.AppUserId">Invoices</a><br /><br />
                    <a asp-action="PartsTable" asp-controller="CustomerTables" asp-route-appUserId="@user.AppUserId">Part Activity</a><br /><br />
                    <a asp-action="QuotesTable" asp-controller="CustomerTables" asp-route-appUserId="@user.AppUserId">Quotes</a><br /><br />
                    <a asp-action="ModifyCustomerAccount" asp-controller="CustomerModifyAccount">Update Acount</a><br /><br />
                }

                @*<a asp-action="AllParts" asp-controller="Parts">View Part Prices</a><br /><br />*@
                <a asp-action="Logout" asp-controller="Account">Sign Out</a><br /><br />
            }
        </div>
        <div style="margin-left: 8%; height: 90vh">
            <br /><br />
            <h1 class="display-3 text-primary" style="text-align: center;">
                @RenderSection("PageName", true)
            </h1>

            <br /><br /><br /><br />

            @RenderBody()
        </div>
    </div>
</body>
</html>