Aztech/ViewModels/AddData/AddShipmentViewModel.cs
using Aztech.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Aztech.ViewModels.AddData
{
    public class AddShipmentViewModel
    {
        public List<string> AllPOKeys { get; set; }
        [Required]
        public string SelectedPO { get; set; }
        [Required]
        public int AppUserId { get; set; }
        [Required]
        public int Invoice { get; set; }
        [Required]
        public string ShipDate { get; set; }
        [Required]
        public string ShipTo { get; set; }
        [Required]
        public string ShipVia { get; set; }
        [Required]
        public string TrackingNum { get; set; }
        [Required]
        public string InvoiceDate { get; set; }
        [Required]
        public string DueDate { get; set; }
        [Required]
        public double InvoiceAmt { get; set; }
        [Required]
        public double BalanceDue { get; set; }

        public void SeedAllPOKeys(List<string> allPOKeys)
        {
            AllPOKeys = allPOKeys.OrderByDescending(r=>r).ToList();

        }
    }
}

Aztech/Controllers/AddDataController.cs
using Aztech.Models;
using Aztech.Services;
using Aztech.ViewModels;
using Aztech.ViewModels.AddData;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Aztech.Controllers
{
    [Authorize]
    public class AddDataController : Controller
    {
        IDataServices dataServices;
        public AddDataController(IDataServices dataServices)
        {
            this.dataServices = dataServices;
        }

        public IActionResult AddDataPage(int appUserId)
        {
            return View(appUserId);
        }

        [HttpGet]
        public IActionResult AddOpenPartOrder(int appUserId)
        {
            OpenPartOrder order = new OpenPartOrder();
            order.AppUserId = appUserId;
            return View(order);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddOpenPartOrder(OpenPartOrder order)
        {
            if (!ModelState.IsValid)
            {
                return View(order);
            }
            try
            {
                Convert.ToDateTime(order.ExpectedShipDate); 
            }
            catch(FormatException ex)
            {
                ModelState.AddModelError("", "Invalid Date Format"); 
                return View(order); 
            }

            order.OrderDate = DateTime.Now.ToString();
            if (dataServices.AddOpenPartOrder(order) != true)
            {
                throw new Exception("Open Part Order Failed To Be Created In Database");
            }
            return RedirectToAction(nameof(AddDataPage), new { order.AppUserId });
        }

        [HttpGet]
        public IActionResult AddShipment(int appUserId)
        {
            if (dataServices.GetOpenPartOrdersGroupedByPO(appUserId) == null) return View("NoOpenOrders");
            AddShipmentViewModel model = new AddShipmentViewModel();
            model.AppUserId = appUserId;
            model.SeedAllPOKeys(dataServices.GetOpenPartOrdersGroupedByPO(appUserId).Keys.ToList());
            return View(model);
        }


        [HttpPost]
        public IActionResult AddShipment(AddShipmentViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.SeedAllPOKeys(dataServices.GetOpenPartOrdersGroupedByPO(model.AppUserId).Keys.ToList());
                return View(model);
            }


            Shipment shipment = new Shipment();
            shipment.AppUserId = model.AppUserId;
            shipment.Invoice = model.Invoice;
            shipment.PONumber = model.SelectedPO;
            shipment.ShipDate = model.ShipDate;
            shipment.ShipTo = model.ShipTo;
            shipment.ShipVia = model.ShipVia;
            shipment.TrackingNum = model.TrackingNum;
            

            Invoice invoice = new Invoice();
            invoice.InvoiceNum = model.Invoice;
            invoice.AppUserId = model.AppUserId;
            invoice.PONum = model.SelectedPO;
            invoice.BalanceDue = model.BalanceDue;
            invoice.InvoiceDate = model.InvoiceDate;
            invoice.InvoiceAmt = model.InvoiceAmt;
            invoice.DueDate = model.DueDate;
            invoice.TrackingNum = model.TrackingNum;
            invoice.ShipTo = model.ShipTo;
            invoice.ShipVia = model.ShipVia;

            try
            {
                Convert.ToDateTime(shipment.ShipDate);
                Convert.ToDateTime(invoice.DueDate);
                Convert.ToDateTime(invoice.InvoiceDate); 
            }
            catch(FormatException ex)
            {
                model.SeedAllPOKeys(dataServices.GetOpenPartOrdersGroupedByPO(model.AppUserId).Keys.ToList());
                ModelState.AddModelError("", "Invalid Date Fromat");
                return View(model);
            }


            int invoiceId = dataServices.AddInvoice(invoice);
            shipment.InvoiceId = invoiceId; 
            int shipmentId = dataServices.AddShipment(shipment);

            Dictionary<string, List<OpenPartOrder>> orderDictionary = dataServices.GetOpenPartOrdersGroupedByPO(model.AppUserId);

            foreach(OpenPartOrder order in orderDictionary[model.SelectedPO])
                {
                ShippedPartOrder shippedOrder = new ShippedPartOrder();
                shippedOrder.CustomPartNum = order.CustomPartNum;
                shippedOrder.AppUserId = order.AppUserId; 
                shippedOrder.Part = order.Part;
                shippedOrder.PartDescription = order.PartDescription;
                shippedOrder.PriceEach = order.PriceEach;
                shippedOrder.QtyShipped = order.QtyShipped;
                shippedOrder.ShippmentId = shipmentId;
                dataServices.AddShippedPartOrder(shippedOrder);
                dataServices.DeleteOpenPartOrder(order);
            }


            return RedirectToAction(nameof(AddDataPage), new { model.AppUserId });
        }

        [HttpGet]
        public IActionResult AddQuote(int appUserId)
        {
            Quote quote = new Quote();
            quote.AppUserId = appUserId; 
            return View(quote);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult AddQuote(Quote quote)
        {
            if (!ModelState.IsValid)
            {
                return View(quote);
            }

            try
            {
                Convert.ToDateTime(quote.OrderedDate);
            }
            catch (FormatException)
            {
                ModelState.AddModelError("", "Invalid date format");
                return View(quote);
            }

            quote.QuoteDate = DateTime.Now.ToShortDateString(); 
            dataServices.AddQuote(quote);
            return RedirectToAction(nameof(AddDataPage), new { quote.AppUserId }); 
        }
    }
}

Aztech/Views/AddData/AddDataPage.cshtml
@model int

@{
    ViewBag.Title = "Add Customer Data";
}

@section PageName{
    Add Data For User @Model
}


<br />
<br />
<br />
<br />
<br />
<br />

<div style="text-align: center" class="display-4">Add Data</div>

<br />
<br />
<br />

<div style="text-align: center">
    <a class="btn btn-dark btn-block" asp-action="AddOpenPartOrder" asp-route-appUserId="@Model">Add Open Order</a>
    <a class="btn btn-dark btn-block" asp-action="AddShipment" asp-route-appUserId="@Model">Add Shipment</a>
    <a class="btn btn-dark btn-block" asp-action="AddQuote" asp-route-appUserId="@Model">Add Quote</a>
</div>

Aztech/Views/AddData/AddOpenPartOrder.cshtml
@model Aztech.Models.OpenPartOrder

@{
    ViewBag.Title = "Add Open Order";
}

@section PageName {
    Add Open Part Order: User @Model.AppUserId
}

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<div class="display-4" style="text-align: center">Add Open Order</div>
<br />
<br />


<form method="post" asp-action="AddOpenPartOrder">
    <table>
        <thead>
            <tr>
                <th>PO#</th>
                <th>Sales Order#</th>
                <th>Expected Ship Date</th>
                <th>Part</th>
                <th>Part Description</th>
                <th>Custom Part Number</th>
                <th>Qty Shipped</th>
                <th>Price Each</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <input type="hidden" asp-for="@Model.AppUserId" />
                    <input type="text" asp-for="@Model.PONum" />
                    <span asp-validation-for="@Model.PONum"></span>
                </td>
                <td>
                    <input type="text" asp-for="@Model.SalesOrderNum" />
                    <span asp-validation-for="@Model.SalesOrderNum"></span>
                </td>
                <td>
                    <input type="text" asp-for="@Model.ExpectedShipDate" />
                    <span asp-validation-for="@Model.ExpectedShipDate"></span>
                </td>
                <td>
                    <input type="text" asp-for="@Model.Part" />
                    <span asp-validation-for="@Model.Part"></span>
                </td>
                <td>
                    <input type="text" asp-for="@Model.PartDescription" />
                    <span asp-validation-for="@Model.PartDescription"></span>
                </td>
                <td>
                    <input type="text" asp-for="@Model.CustomPartNum" />
                    <span asp-validation-for="@Model.CustomPartNum"></span>
                </td>
                <td>
                    <input type="text" asp-for="@Model.QtyShipped" />
                    <span asp-validation-for="@Model.QtyShipped"></span>
                </td>
                <td>
                    <input type="text" asp-for="@Model.PriceEach" />
                    <span asp-validation-for="@Model.PriceEach"></span>
                </td>
            </tr>
        </tbody>
    </table>
    <br />
    <br />
    <div asp-validation-summary="ModelOnly"></div>
    <div style="text-align: center"><input class="btn btn-primary" type="submit" value="Create Open Order" /></div>
</form>

Aztech/Views/AddData/AddQuote.cshtml
@model Aztech.Models.Quote

@{
    ViewBag.Title = "Add Quote";
}

@section PageName{
    Add Quote User: @Model.AppUserId
}

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<div class="display-4" style="text-align: center">Add Quote</div>
<br />
<br />


<form asp-action="AddQuote" asp-controller="AddData" method="post">
    <table class="table">
        <thead>
            <tr>
                <th>RFQ</th>
                <th>Ordered Date</th>
                <th>Part</th>
                <th>Part Description</th>
                <th>Qty</th>
                <th>Price Ea</th>
                <th>Customer Part#</th>
                <th>Notes</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <input type="hidden" asp-for="AppUserId" />
                    <input type="text" asp-for="RFQ" />
                    <span asp-validation-for="RFQ"></span>
                </td>
                <td>
                    <input type="text" asp-for="OrderedDate" />
                    <span asp-validation-for="OrderedDate"></span>
                </td>
                <td>
                    <input type="text" asp-for="Part" />
                    <span asp-validation-for="Part"></span>
                </td>
                <td>
                    <input type="text" asp-for="PartDescription" />
                    <span asp-validation-for="PartDescription"></span>
                </td>
                <td>
                    <input type="text" asp-for="Qty" />
                    <span asp-validation-for="Qty"></span>
                </td>
                <td>
                    <input type="text" asp-for="PriceEa" />
                    <span asp-validation-for="PriceEa"></span>
                </td>
                <td>
                    <input type="text" asp-for="CustomerPartNum" />
                    <span asp-validation-for="CustomerPartNum"></span>
                </td>
                <td>
                    <textarea asp-for="Notes" cols="20" rows="3"></textarea>
                    <span asp-validation-for="Notes"></span>
                </td>
            </tr>
        </tbody>
    </table>
    <div asp-validation-summary="ModelOnly"></div>
    <div style="text-align: center"><input class="btn btn-primary" type="submit" value="Create Quote" /></div>
</form>

Aztech/Views/AddData/AddShipment.cshtml
@model Aztech.ViewModels.AddData.AddShipmentViewModel

@{
    ViewBag.Title = "Add Shipment";
}

@section PageName {
    Add Shipment: User @Model.AppUserId
}

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<div class="display-4" style="text-align: center">Add Shipment</div>
<br />
<br />


<form method="post" asp-action="AddShipment">
    <table class="table">
        <caption style="text-align:center">Shipment Information</caption>
        <thead>
            <tr>
                <th>PO#</th>
                <th>Invoice</th>
                <th>ShipDate</th>
                <th>ShipTo</th>
                <th>ShipVia</th>
                <th>Tracking#</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <input type="hidden" asp-for="@Model.AppUserId" />
                    <select asp-for="SelectedPO" asp-items="@new SelectList(Model.AllPOKeys)"><option></option></select>
                    <span asp-validation-for="@Model.SelectedPO"></span>
                </td>
                <td>
                    <input type="text" asp-for="@Model.Invoice" />
                    <span asp-validation-for="@Model.Invoice"></span>
                </td>
                <td>
                    <input type="text" asp-for="@Model.ShipDate" />
                    <span asp-validation-for="@Model.ShipDate"></span>
                </td>
                <td>
                    <input type="text" asp-for="@Model.ShipTo" />
                    <span asp-validation-for="@Model.ShipTo"></span>
                </td>
                <td>
                    <input type="text" asp-for="@Model.ShipVia" />
                    <span asp-validation-for="@Model.ShipVia"></span>
                </td>
                <td>
                    <input type="text" asp-for="@Model.TrackingNum" />
                    <span asp-validation-for="@Model.TrackingNum"></span>
                </td>
            </tr>
        </tbody>
    </table>
    <br />
    <br />
    <table class="table">
        <caption style="text-align:center">Invoice Information</caption>
        <thead>
            <tr>
                <th>Invoice Date</th>
                <th>Due Date</th>
                <th>Invoice Amt</th>
                <th>Balance Due</th>
                <th>Ship To</th>
                <th>Ship Via</th>
                <th>Tracking#</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <input type="text" asp-for="@Model.InvoiceDate" />
                    <span asp-validation-for="InvoiceDate"></span>
                </td>
                <td>
                    <input type="text" asp-for="@Model.DueDate" />
                    <span asp-validation-for="DueDate"></span>
                </td>
                <td>
                    <input type="text" asp-for="@Model.InvoiceAmt" />
                    <span asp-validation-for="InvoiceAmt"></span>
                </td>
                <td>
                    <input type="text" asp-for="@Model.BalanceDue" />
                    <span asp-validation-for="BalanceDue"></span>
                </td>
                <td>
                    <input type="text" asp-for="@Model.ShipTo" />
                    <span asp-validation-for="ShipTo"></span>
                </td>
                <td>
                    <input type="text" asp-for="@Model.ShipVia" />
                    <span asp-validation-for="ShipVia"></span>
                </td>
                <td>
                    <input type="text" asp-for="@Model.TrackingNum" />
                    <span asp-validation-for="TrackingNum"></span>
                </td>
            </tr>
        </tbody>
    </table>


    <div style="text-align: center"><input style="margin-top: 5%" class="btn btn-primary" type="submit" value="Create Shipment" /></div>
    <div asp-validation-summary="ModelOnly"></div>
</form>

Aztech/Views/AddData/NoOpenOrders.cshtml
@{ 
    ViewBag.Title = "No Open Orders";
}

@section PageName {
    No Open Orders
}

<p style="text-align: center">There are no open orders to ship for this customer.</p>